export const GATEWAY_ENV = Symbol('GATEWAY_ENV');
export const GATEWAY_LOGGER = Symbol('GATEWAY_LOGGER');
export const GATEWAY_METRICS_REGISTRY = Symbol('GATEWAY_METRICS_REGISTRY');
export const GATEWAY_DASHBOARD_STORE = Symbol('GATEWAY_DASHBOARD_STORE');
export const GATEWAY_BACKEND_REGISTRY = Symbol('GATEWAY_BACKEND_REGISTRY');
export const GATEWAY_DISPATCHER = Symbol('GATEWAY_DISPATCHER');
export const GATEWAY_MCP_ROUTER = Symbol('GATEWAY_MCP_ROUTER');

export const GATEWAY_PERSISTENCE_PORTS = Symbol('GATEWAY_PERSISTENCE_PORTS');
export const GATEWAY_PERSISTENCE_HEALTH = Symbol('GATEWAY_PERSISTENCE_HEALTH');
