import {
  UV_ASSIGNMENTS_REQUIRED,
  UV_ASSIGNMENT_CUBE_IDS_STRING_ARRAY,
  UV_ASSIGNMENT_CUBE_NAMES_STRING_ARRAY,
  UV_ASSIGNMENT_FACES_NON_EMPTY,
  UV_ASSIGNMENT_FACES_REQUIRED,
  UV_ASSIGNMENT_INVALID_FACE,
  UV_ASSIGNMENT_OBJECT_REQUIRED,
  UV_ASSIGNMENT_TARGET_REQUIRED,
  UV_ASSIGNMENT_UV_FORMAT,
  UV_ASSIGNMENT_UV_NUMBERS,
  UV_ATLAS_CUBE_MISSING,
  UV_ATLAS_DERIVE_SIZE_FAILED,
  UV_ATLAS_EXCEEDS_MAX,
  UV_ATLAS_MAX_RESOLUTION_POSITIVE,
  UV_ATLAS_OVERFLOW,
  UV_ATLAS_RESOLUTION_POSITIVE,
  UV_ATLAS_UV_SIZE_EXCEEDS,
  UV_BOUNDS_NEGATIVE,
  UV_BOUNDS_ORDER,
  UV_BOUNDS_OUT_OF_BOUNDS,
  UV_OVERLAP_FIX,
  UV_OVERLAP_MESSAGE,
  UV_PAINT_ANCHOR_FORMAT,
  UV_PAINT_ANCHOR_NUMBERS,
  UV_PAINT_MAPPING_INVALID,
  UV_PAINT_NO_BOUNDS,
  UV_PAINT_NO_RECTS,
  UV_PAINT_OBJECT_REQUIRED,
  UV_PAINT_PADDING_EXCEEDS_RECT,
  UV_PAINT_PADDING_INVALID,
  UV_PAINT_PATTERN_UNAVAILABLE,
  UV_PAINT_RECT_INVALID,
  UV_PAINT_RECT_OUTSIDE_BOUNDS,
  UV_PAINT_RECTS_REQUIRED,
  UV_PAINT_SCOPE_INVALID,
  UV_PAINT_SOURCE_AXIS_INTEGER,
  UV_PAINT_SOURCE_AXIS_POSITIVE,
  UV_PAINT_SOURCE_DATA_MISMATCH,
  UV_PAINT_SOURCE_EXCEEDS_MAX,
  UV_PAINT_SOURCE_OBJECT,
  UV_PAINT_SOURCE_POSITIVE,
  UV_PAINT_SOURCE_REQUIRED,
  UV_PAINT_SOURCE_TARGET_POSITIVE,
  UV_PAINT_TARGET_CUBE_IDS_REQUIRED,
  UV_PAINT_TARGET_CUBE_IDS_STRING,
  UV_PAINT_TARGET_CUBE_NAMES_REQUIRED,
  UV_PAINT_TARGET_CUBE_NAMES_STRING,
  UV_PAINT_TARGET_FACES_INVALID,
  UV_PAINT_TARGET_FACES_REQUIRED,
  UV_PAINT_TARGET_FACES_NOT_FOUND,
  UV_PAINT_TARGET_CUBES_NOT_FOUND,
  UV_PAINT_TARGET_OBJECT,
  UV_PAINT_USAGE_MISSING,
  UV_SCALE_FIX,
  UV_SCALE_MESSAGE,
  UV_USAGE_CHANGED_FIX,
  UV_USAGE_CHANGED_MESSAGE
} from '../messages';

export const buildUvAssignmentMessages = () => ({
  assignmentsRequired: UV_ASSIGNMENTS_REQUIRED,
  assignmentObjectRequired: UV_ASSIGNMENT_OBJECT_REQUIRED,
  targetRequired: UV_ASSIGNMENT_TARGET_REQUIRED,
  cubeIdsStringArray: UV_ASSIGNMENT_CUBE_IDS_STRING_ARRAY,
  cubeNamesStringArray: UV_ASSIGNMENT_CUBE_NAMES_STRING_ARRAY,
  facesRequired: UV_ASSIGNMENT_FACES_REQUIRED,
  facesNonEmpty: UV_ASSIGNMENT_FACES_NON_EMPTY,
  invalidFace: UV_ASSIGNMENT_INVALID_FACE,
  uvFormat: UV_ASSIGNMENT_UV_FORMAT,
  uvNumbers: UV_ASSIGNMENT_UV_NUMBERS
});

export const buildUvBoundsMessages = () => ({
  negative: UV_BOUNDS_NEGATIVE,
  order: UV_BOUNDS_ORDER,
  outOfBounds: UV_BOUNDS_OUT_OF_BOUNDS
});

export const buildUvAtlasMessages = () => ({
  resolutionPositive: UV_ATLAS_RESOLUTION_POSITIVE,
  maxResolutionPositive: UV_ATLAS_MAX_RESOLUTION_POSITIVE,
  exceedsMax: UV_ATLAS_EXCEEDS_MAX,
  cubeMissing: UV_ATLAS_CUBE_MISSING,
  deriveSizeFailed: UV_ATLAS_DERIVE_SIZE_FAILED,
  uvSizeExceeds: UV_ATLAS_UV_SIZE_EXCEEDS,
  overflow: UV_ATLAS_OVERFLOW
});

export const buildUvGuardMessages = () => ({
  usageChangedMessage: UV_USAGE_CHANGED_MESSAGE,
  usageChangedFix: UV_USAGE_CHANGED_FIX,
  overlapMessage: UV_OVERLAP_MESSAGE,
  overlapFix: UV_OVERLAP_FIX,
  scaleMessage: UV_SCALE_MESSAGE,
  scaleFix: UV_SCALE_FIX
});

export const buildUvPaintMessages = () => ({
  usageMissing: UV_PAINT_USAGE_MISSING,
  targetCubesNotFound: UV_PAINT_TARGET_CUBES_NOT_FOUND,
  targetFacesNotFound: UV_PAINT_TARGET_FACES_NOT_FOUND,
  noRects: UV_PAINT_NO_RECTS,
  noBounds: UV_PAINT_NO_BOUNDS,
  objectRequired: UV_PAINT_OBJECT_REQUIRED,
  scopeInvalid: UV_PAINT_SCOPE_INVALID,
  mappingInvalid: UV_PAINT_MAPPING_INVALID,
  paddingInvalid: UV_PAINT_PADDING_INVALID,
  anchorFormat: UV_PAINT_ANCHOR_FORMAT,
  anchorNumbers: UV_PAINT_ANCHOR_NUMBERS,
  sourceObject: UV_PAINT_SOURCE_OBJECT,
  sourceRequired: UV_PAINT_SOURCE_REQUIRED,
  sourcePositive: UV_PAINT_SOURCE_POSITIVE,
  sourceExceedsMax: UV_PAINT_SOURCE_EXCEEDS_MAX,
  targetObject: UV_PAINT_TARGET_OBJECT,
  targetCubeIdsRequired: UV_PAINT_TARGET_CUBE_IDS_REQUIRED,
  targetCubeIdsString: UV_PAINT_TARGET_CUBE_IDS_STRING,
  targetCubeNamesRequired: UV_PAINT_TARGET_CUBE_NAMES_REQUIRED,
  targetCubeNamesString: UV_PAINT_TARGET_CUBE_NAMES_STRING,
  targetFacesRequired: UV_PAINT_TARGET_FACES_REQUIRED,
  targetFacesInvalid: UV_PAINT_TARGET_FACES_INVALID
});

export const buildUvPaintRectMessages = () => ({
  rectInvalid: UV_PAINT_RECT_INVALID,
  paddingExceedsRect: UV_PAINT_PADDING_EXCEEDS_RECT,
  rectOutsideBounds: UV_PAINT_RECT_OUTSIDE_BOUNDS
});

export const buildUvPaintPixelMessages = () => ({
  rectsRequired: UV_PAINT_RECTS_REQUIRED,
  sourceTargetPositive: UV_PAINT_SOURCE_TARGET_POSITIVE,
  sourceDataMismatch: UV_PAINT_SOURCE_DATA_MISMATCH,
  rects: buildUvPaintRectMessages()
});

export const buildUvPaintSourceMessages = () => ({
  axisPositive: UV_PAINT_SOURCE_AXIS_POSITIVE,
  axisInteger: UV_PAINT_SOURCE_AXIS_INTEGER,
  exceedsMax: UV_PAINT_SOURCE_EXCEEDS_MAX
});

export const buildUvPaintRuntimeMessages = () => ({
  patternUnavailable: UV_PAINT_PATTERN_UNAVAILABLE
});
